### ISSUE TITLE
Update version of prom/prometheus to v2.45.0

### ISSUE THREAD

**Issue by romachyzh** [alexzhyshko/PrometheusLab#1]
Prometheus v2.1.0 is outdated. You should update to a newer version that uses OCI Format or Docker Image manifest v2, schema 2.

1️⃣ Update docker-compose.yml

📌 Change this:
```yaml
services:
  prometheus:
    image: prom/prometheus:v2.1.0
```

📌 To:
```yaml
services:
  prometheus:
    image: prom/prometheus:v2.45.0
```
